version: '3.8'
services:
  samu3le_restaurant_frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: samu3le_restaurant_frontend
    volumes:
       - ./:/usr/src/app
       - /usr/src/app/node_modules