export const route = "auth";

export const SIGN_IN_FETCH_REQUEST = "SIGN_IN_FETCH_REQUEST";
export const SIGN_IN_FETCH_SUCCESS = "SIGN_IN_FETCH_SUCCESS";
export const SIGN_IN_FETCH_FAILURE = "SIGN_IN_FETCH_FAILURE";

export const SIGN_OUT_FETCH_REQUEST = "SIGN_OUT_FETCH_REQUEST";
export const SIGN_OUT_FETCH_SUCCESS = "SIGN_OUT_FETCH_SUCCESS";
export const SIGN_OUT_FETCH_FAILURE = "SIGN_OUT_FETCH_FAILURE";

export const SIGN_UP_FETCH_REQUEST = "SIGN_UP_FETCH_REQUEST";
export const SIGN_UP_FETCH_SUCCESS = "SIGN_UP_FETCH_SUCCESS";
export const SIGN_UP_FETCH_FAILURE = "SIGN_UP_FETCH_FAILURE";
