export const route = "warehouse";

export const LIST_SET_PARAMS = "LIST_SET_PARAMS";
export const LIST_FETCH_REQUEST = "LIST_FETCH_REQUEST";
export const LIST_FETCH_SUCCESS = "LIST_FETCH_SUCCESS";
export const LIST_FETCH_FAILURE = "LIST_FETCH_FAILURE";

export const BUY_FETCH_REQUEST = "BUY_FETCH_REQUEST";
export const BUY_FETCH_SUCCESS = "BUY_FETCH_SUCCESS";
export const BUY_FETCH_FAILURE = "BUY_FETCH_FAILURE";

export const STATE_CHANGE_FETCH_REQUEST = "STATE_CHANGE_FETCH_REQUEST";
export const STATE_CHANGE_FETCH_SUCCESS = "STATE_CHANGE_FETCH_SUCCESS";
export const STATE_CHANGE_FETCH_FAILURE = "STATE_CHANGE_FETCH_FAILURE";
